-- CISPA Platform Seed Data
-- Core 30 assessment questions across 6 dimensions

-- Insert core assessment questions
INSERT INTO public.questions (question_text, question_type, dimension, module, order_index, weight, help_text, options) VALUES

-- FINANCIAL DIMENSION (5 questions)
('What is your company''s annual recurring revenue (ARR) or annual revenue for the most recent completed year?', 'number', 'financial', 'core', 1, 1.0, 'Enter the full annual amount. This helps assess company scale and growth trajectory.', '[]'),

('What has been your average annual revenue growth rate over the past 3 years?', 'scale', 'financial', 'core', 2, 1.0, 'Select the range that best represents your average year-over-year growth.', '[{"value": "negative", "label": "Negative growth", "score": 1}, {"value": "0-10", "label": "0-10%", "score": 2}, {"value": "11-25", "label": "11-25%", "score": 3}, {"value": "26-50", "label": "26-50%", "score": 4}, {"value": "51-100", "label": "51-100%", "score": 5}, {"value": "100+", "label": "Over 100%", "score": 6}]'),

('How many months of operating cash runway does your company currently have?', 'scale', 'financial', 'core', 3, 1.0, 'Based on current burn rate and available cash/committed funding.', '[{"value": "0-3", "label": "0-3 months", "score": 1}, {"value": "4-6", "label": "4-6 months", "score": 2}, {"value": "7-12", "label": "7-12 months", "score": 3}, {"value": "13-18", "label": "13-18 months", "score": 4}, {"value": "19-24", "label": "19-24 months", "score": 5}, {"value": "24+", "label": "24+ months", "score": 6}]'),

('What is your gross margin percentage?', 'scale', 'financial', 'core', 4, 1.0, 'Gross margin = (Revenue - Cost of Goods Sold) / Revenue × 100', '[{"value": "negative", "label": "Negative margin", "score": 1}, {"value": "0-20", "label": "0-20%", "score": 2}, {"value": "21-40", "label": "21-40%", "score": 3}, {"value": "41-60", "label": "41-60%", "score": 4}, {"value": "61-80", "label": "61-80%", "score": 5}, {"value": "80+", "label": "80%+", "score": 6}]'),

('Do you have audited financial statements for the past 2 years?', 'multiple_choice', 'financial', 'core', 5, 1.0, 'Audited financials provide credibility and are often required for institutional investment.', '[{"value": "yes_both", "label": "Yes, for both years", "score": 6}, {"value": "yes_one", "label": "Yes, for one year", "score": 4}, {"value": "reviewed", "label": "No, but we have reviewed financials", "score": 3}, {"value": "compiled", "label": "No, only compiled financials", "score": 2}, {"value": "none", "label": "No professional financial statements", "score": 1}]'),

-- OPERATIONAL DIMENSION (5 questions)
('How would you rate your company''s operational efficiency and process maturity?', 'scale', 'operational', 'core', 6, 1.0, 'Consider standardized processes, documentation, and operational metrics.', '[{"value": "ad_hoc", "label": "Ad-hoc, informal processes", "score": 1}, {"value": "basic", "label": "Basic processes documented", "score": 2}, {"value": "standardized", "label": "Standardized processes across teams", "score": 3}, {"value": "optimized", "label": "Optimized with regular improvement", "score": 4}, {"value": "best_in_class", "label": "Best-in-class operational excellence", "score": 5}]'),

('What is your current team size (full-time employees)?', 'number', 'operational', 'core', 7, 1.0, 'Include all full-time employees across all functions.', '[]'),

('How many key management positions do you have strong succession plans for?', 'scale', 'operational', 'core', 8, 1.0, 'Key positions include C-level, VP-level, and other critical roles.', '[{"value": "none", "label": "No succession plans", "score": 1}, {"value": "few", "label": "1-2 positions covered", "score": 2}, {"value": "some", "label": "About half of key positions", "score": 3}, {"value": "most", "label": "Most key positions covered", "score": 4}, {"value": "all", "label": "All key positions have plans", "score": 5}]'),

('What percentage of your revenue comes from your top 3 customers?', 'scale', 'operational', 'core', 9, 1.0, 'Customer concentration risk is important for valuation and risk assessment.', '[{"value": "80+", "label": "80%+", "score": 1}, {"value": "60-79", "label": "60-79%", "score": 2}, {"value": "40-59", "label": "40-59%", "score": 3}, {"value": "20-39", "label": "20-39%", "score": 4}, {"value": "0-19", "label": "Less than 20%", "score": 5}]'),

('How robust is your company''s data and reporting infrastructure?', 'scale', 'operational', 'core', 10, 1.0, 'Consider real-time dashboards, KPI tracking, and data-driven decision making.', '[{"value": "manual", "label": "Mostly manual reporting", "score": 1}, {"value": "basic", "label": "Basic automated reports", "score": 2}, {"value": "good", "label": "Good dashboards and KPIs", "score": 3}, {"value": "advanced", "label": "Advanced analytics and insights", "score": 4}, {"value": "best_in_class", "label": "Best-in-class data infrastructure", "score": 5}]'),

-- MARKET DIMENSION (5 questions)
('How large is your total addressable market (TAM)?', 'scale', 'market', 'core', 11, 1.0, 'Estimate the total market size for your product/service globally.', '[{"value": "under_100m", "label": "Under $100M", "score": 2}, {"value": "100m_1b", "label": "$100M - $1B", "score": 3}, {"value": "1b_10b", "label": "$1B - $10B", "score": 4}, {"value": "10b_100b", "label": "$10B - $100B", "score": 5}, {"value": "over_100b", "label": "Over $100B", "score": 6}]'),

('What is your current market share in your primary market?', 'scale', 'market', 'core', 12, 1.0, 'Estimate your share of the addressable market you''re actively competing in.', '[{"value": "under_1", "label": "Less than 1%", "score": 2}, {"value": "1_5", "label": "1-5%", "score": 3}, {"value": "6_15", "label": "6-15%", "score": 4}, {"value": "16_30", "label": "16-30%", "score": 5}, {"value": "over_30", "label": "Over 30%", "score": 6}]'),

('How differentiated is your product/service offering?', 'scale', 'market', 'core', 13, 1.0, 'Consider uniqueness, competitive moats, and barriers to entry.', '[{"value": "commodity", "label": "Commodity/highly competitive", "score": 1}, {"value": "some_diff", "label": "Some differentiation", "score": 2}, {"value": "clear_diff", "label": "Clear competitive advantages", "score": 3}, {"value": "strong_moat", "label": "Strong competitive moat", "score": 4}, {"value": "unique", "label": "Unique/patent-protected", "score": 5}]'),

('What is your Net Promoter Score (NPS) or customer satisfaction rating?', 'scale', 'market', 'core', 14, 1.0, 'If you don''t measure NPS, estimate based on customer feedback and retention.', '[{"value": "negative", "label": "Negative/Poor satisfaction", "score": 1}, {"value": "0_30", "label": "0-30 (Needs improvement)", "score": 2}, {"value": "31_50", "label": "31-50 (Good)", "score": 3}, {"value": "51_70", "label": "51-70 (Excellent)", "score": 4}, {"value": "71+", "label": "71+ (World-class)", "score": 5}]'),

('How predictable and recurring is your revenue model?', 'scale', 'market', 'core', 15, 1.0, 'Consider subscription models, contracts, and revenue visibility.', '[{"value": "project", "label": "Project-based/unpredictable", "score": 1}, {"value": "some_recurring", "label": "Some recurring elements", "score": 2}, {"value": "mostly_recurring", "label": "Mostly recurring revenue", "score": 3}, {"value": "subscription", "label": "Subscription/contract-based", "score": 4}, {"value": "long_contracts", "label": "Long-term contracts (2+ years)", "score": 5}]'),

-- TECHNOLOGY DIMENSION (5 questions)
('How would you rate your technology infrastructure and scalability?', 'scale', 'technology', 'core', 16, 1.0, 'Consider system architecture, performance, and ability to handle growth.', '[{"value": "basic", "label": "Basic/legacy systems", "score": 1}, {"value": "functional", "label": "Functional but limited", "score": 2}, {"value": "good", "label": "Good scalability", "score": 3}, {"value": "advanced", "label": "Advanced/cloud-native", "score": 4}, {"value": "best_in_class", "label": "Best-in-class architecture", "score": 5}]'),

('What percentage of your technology assets are proprietary vs. third-party?', 'scale', 'technology', 'core', 17, 1.0, 'Proprietary technology can provide competitive advantages and IP value.', '[{"value": "mostly_3rd", "label": "Mostly third-party (80%+)", "score": 2}, {"value": "mixed", "label": "Mixed (40-60% proprietary)", "score": 3}, {"value": "mostly_prop", "label": "Mostly proprietary (60%+)", "score": 4}, {"value": "all_prop", "label": "Fully proprietary platform", "score": 5}]'),

('How comprehensive is your cybersecurity and data protection?', 'scale', 'technology', 'core', 18, 1.0, 'Consider security policies, compliance certifications, and incident history.', '[{"value": "basic", "label": "Basic security measures", "score": 1}, {"value": "standard", "label": "Standard security protocols", "score": 2}, {"value": "good", "label": "Good security posture", "score": 3}, {"value": "enterprise", "label": "Enterprise-grade security", "score": 4}, {"value": "certified", "label": "Security certified (SOC2, ISO27001)", "score": 5}]'),

('Do you have strong intellectual property protection?', 'multiple_choice', 'technology', 'core', 19, 1.0, 'Consider patents, trademarks, trade secrets, and IP strategy.', '[{"value": "none", "label": "No formal IP protection", "score": 1}, {"value": "basic", "label": "Basic trademarks/copyrights", "score": 2}, {"value": "some_patents", "label": "Some patents filed", "score": 3}, {"value": "patent_portfolio", "label": "Strong patent portfolio", "score": 4}, {"value": "comprehensive", "label": "Comprehensive IP strategy", "score": 5}]'),

('How automated are your key business processes?', 'scale', 'technology', 'core', 20, 1.0, 'Consider automation in operations, customer service, finance, and other core functions.', '[{"value": "manual", "label": "Mostly manual processes", "score": 1}, {"value": "some_auto", "label": "Some automation implemented", "score": 2}, {"value": "good_auto", "label": "Good automation coverage", "score": 3}, {"value": "highly_auto", "label": "Highly automated operations", "score": 4}, {"value": "ai_powered", "label": "AI-powered automation", "score": 5}]'),

-- LEGAL DIMENSION (5 questions)
('How compliant is your company with relevant industry regulations?', 'scale', 'legal', 'core', 21, 1.0, 'Consider industry-specific regulations and compliance status.', '[{"value": "non_compliant", "label": "Non-compliant/at risk", "score": 1}, {"value": "partially", "label": "Partially compliant", "score": 2}, {"value": "mostly", "label": "Mostly compliant", "score": 3}, {"value": "fully", "label": "Fully compliant", "score": 4}, {"value": "exceeds", "label": "Exceeds requirements", "score": 5}]'),

('Are there any pending or threatened legal issues?', 'multiple_choice', 'legal', 'core', 22, 1.0, 'Include litigation, regulatory issues, or other legal concerns.', '[{"value": "major", "label": "Yes, major issues", "score": 1}, {"value": "minor", "label": "Yes, minor issues", "score": 2}, {"value": "potential", "label": "Some potential issues", "score": 3}, {"value": "minimal", "label": "Minimal concerns", "score": 4}, {"value": "none", "label": "No legal issues", "score": 5}]'),

('How clean is your corporate structure and cap table?', 'scale', 'legal', 'core', 23, 1.0, 'Consider entity structure, shareholder agreements, and equity clarity.', '[{"value": "complex", "label": "Complex/needs cleanup", "score": 1}, {"value": "some_issues", "label": "Some structural issues", "score": 2}, {"value": "mostly_clean", "label": "Mostly clean structure", "score": 3}, {"value": "clean", "label": "Clean and well-documented", "score": 4}, {"value": "optimized", "label": "Optimized for transactions", "score": 5}]'),

('Do you have proper employment agreements and IP assignments?', 'multiple_choice', 'legal', 'core', 24, 1.0, 'Ensure all employees have signed agreements assigning IP to the company.', '[{"value": "none", "label": "No formal agreements", "score": 1}, {"value": "some", "label": "Some employees covered", "score": 2}, {"value": "most", "label": "Most employees covered", "score": 3}, {"value": "all_current", "label": "All current employees", "score": 4}, {"value": "all_historical", "label": "All employees (including historical)", "score": 5}]'),

('How comprehensive are your contracts with key customers and suppliers?', 'scale', 'legal', 'core', 25, 1.0, 'Consider contract terms, protections, and enforceability.', '[{"value": "informal", "label": "Mostly informal agreements", "score": 1}, {"value": "basic", "label": "Basic written contracts", "score": 2}, {"value": "standard", "label": "Standard contract terms", "score": 3}, {"value": "comprehensive", "label": "Comprehensive legal protections", "score": 4}, {"value": "optimized", "label": "Optimized for business value", "score": 5}]'),

-- STRATEGIC DIMENSION (5 questions)
('How clear and achievable is your long-term strategic vision?', 'scale', 'strategic', 'core', 26, 1.0, 'Consider the clarity, feasibility, and team alignment around your 3-5 year vision.', '[{"value": "unclear", "label": "Unclear or frequently changing", "score": 1}, {"value": "basic", "label": "Basic vision exists", "score": 2}, {"value": "clear", "label": "Clear and documented", "score": 3}, {"value": "detailed", "label": "Detailed with milestones", "score": 4}, {"value": "inspiring", "label": "Inspiring and widely shared", "score": 5}]'),

('How strong is your management team and leadership depth?', 'scale', 'strategic', 'core', 27, 1.0, 'Consider experience, track record, and leadership capabilities.', '[{"value": "inexperienced", "label": "Inexperienced team", "score": 1}, {"value": "developing", "label": "Developing capabilities", "score": 2}, {"value": "competent", "label": "Competent leadership", "score": 3}, {"value": "strong", "label": "Strong experienced team", "score": 4}, {"value": "exceptional", "label": "Exceptional leadership", "score": 5}]'),

('How well-defined are your key performance indicators (KPIs)?', 'scale', 'strategic', 'core', 28, 1.0, 'Consider KPI definition, measurement, and use in decision-making.', '[{"value": "none", "label": "No defined KPIs", "score": 1}, {"value": "basic", "label": "Basic metrics tracked", "score": 2}, {"value": "good", "label": "Good KPI framework", "score": 3}, {"value": "comprehensive", "label": "Comprehensive measurement", "score": 4}, {"value": "predictive", "label": "Predictive and leading indicators", "score": 5}]'),

('How attractive is your company for potential strategic acquirers?', 'scale', 'strategic', 'core', 29, 1.0, 'Consider strategic fit, market position, and acquisition rationale.', '[{"value": "unattractive", "label": "Limited strategic appeal", "score": 1}, {"value": "some_appeal", "label": "Some strategic value", "score": 2}, {"value": "appealing", "label": "Appealing to acquirers", "score": 3}, {"value": "highly_attractive", "label": "Highly attractive asset", "score": 4}, {"value": "must_have", "label": "Must-have strategic asset", "score": 5}]'),

('How scalable is your current business model?', 'scale', 'strategic', 'core', 30, 1.0, 'Consider ability to grow without proportional increases in costs.', '[{"value": "not_scalable", "label": "Not scalable", "score": 1}, {"value": "limited", "label": "Limited scalability", "score": 2}, {"value": "moderately", "label": "Moderately scalable", "score": 3}, {"value": "highly", "label": "Highly scalable", "score": 4}, {"value": "exponential", "label": "Exponentially scalable", "score": 5}]');

-- Create sample investors for Sprint 2 investor matching
INSERT INTO public.investors (name, type, focus_areas, investment_range_min, investment_range_max, geographic_focus, criteria_weights, description, website) VALUES

('TechVentures Capital', 'vc', '["SaaS", "Fintech", "Healthcare IT"]', 1000000, 10000000, '["North America", "Europe"]', '{"financial": 0.25, "market": 0.20, "technology": 0.25, "operational": 0.15, "legal": 0.05, "strategic": 0.10}', 'Early to growth-stage venture capital focused on B2B technology companies.', 'https://techventures.com'),

('Growth Partners PE', 'pe', '["Manufacturing", "Business Services", "Technology"]', 10000000, 100000000, '["North America"]', '{"financial": 0.30, "operational": 0.25, "strategic": 0.20, "market": 0.15, "legal": 0.05, "technology": 0.05}', 'Private equity firm specializing in growth capital and operational improvements.', 'https://growthpartners.com'),

('Strategic Innovations Fund', 'strategic', '["AI/ML", "IoT", "Cybersecurity"]', 5000000, 50000000, '["Global"]', '{"technology": 0.35, "strategic": 0.25, "market": 0.20, "financial": 0.10, "operational": 0.05, "legal": 0.05}', 'Corporate venture arm focused on strategic technology acquisitions.', 'https://sinovations.com'),

('Regional Capital Partners', 'vc', '["Healthcare", "Consumer", "B2B Services"]', 2000000, 25000000, '["North America"]', '{"financial": 0.20, "market": 0.25, "operational": 0.20, "strategic": 0.15, "technology": 0.10, "legal": 0.10}', 'Multi-stage venture capital with operational support focus.', 'https://regionalcap.com'),

('Enterprise Value Partners', 'pe', '["Enterprise Software", "Business Services"]', 25000000, 200000000, '["North America", "Europe"]', '{"financial": 0.35, "operational": 0.20, "strategic": 0.20, "market": 0.15, "technology": 0.05, "legal": 0.05}', 'Middle-market private equity focused on enterprise software and services.', 'https://enterprisevalue.com');